### Sections
- 1. Select a single element from 2D array
- 2. Select a row(s) from 2D array
- 3. Select column(s) from 2D array
- 4. Numpy unique operation

### Libraries
- NumPy

In [1]:
# Effective data-driven science & computation requires understanding how data is stored & manipulated
import numpy as np

# Create an array
data = np.array(([21, 22, 23], 
                 [11, 22, 33], 
                 [43, 77, 89]))

print(f"Object type: {type(data)}")
print(f"Array shape: {data.shape}")

Object type: <class 'numpy.ndarray'>
Array shape: (3, 3)


### 1. Select a single element from 2D array

In [2]:
# View 2D array
display(data)

# [Row index, Column index]
display(data[0,0])

# ([Row index][Column index])
display(data[0][0])

array([[21, 22, 23],
       [11, 22, 33],
       [43, 77, 89]])

21

21

### 2. Select a row(s) from 2D array

In [3]:
# View 2D array
display(data)

# [Row index]
display(data[1])

# [Row index : Row index]
display(data[0:2])

array([[21, 22, 23],
       [11, 22, 33],
       [43, 77, 89]])

array([11, 22, 33])

array([[21, 22, 23],
       [11, 22, 33]])

### 3. Select column(s) from 2D array

In [4]:
# View 2D array
display(data)

# A single column [All Rows, Column index]
display(data[:, 0])

# Multiple columns [All Rows, Column index : Column index]
display(data[:, 1:3])

array([[21, 22, 23],
       [11, 22, 33],
       [43, 77, 89]])

array([21, 11, 43])

array([[22, 23],
       [22, 33],
       [77, 89]])

### 4. Numpy unique operation

In [5]:
# Create an array
data = np.array(([10, 10, 23], 
                 [11, 20, 33], 
                 [12, 30, 89]))

# Return unique values of a specific row [Row index]
display(np.unique(data[0]))

# Return the number of unique values in a specific row [Row index]
print(len(np.unique(data[0])))

# Return unique values of a specific column [All Rows, Column index]
display(np.unique(data[:, 1]))

array([10, 23])

2


array([10, 20, 30])